version: '3.8'

services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "5000:7000"
    depends_on:
      - recommender
    environment:
      - FLASK_ENV=development
      - RECOMMENDER_URL=http://recommender:7001

  recommender:
    build:
      context: ./recommender
    ports:
      - "5001:7001"
    environment:
      - FLASK_ENV=development